version: '3.8'

networks:
  app_network:  # Explicitly define the network
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: basket
    ports:
      - "5432:5432"
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: projet-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: projet-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:
